# config file for Twitter API keys

api_key: 6JjI4pskP4blS4SOyUrIO4iwW
api_secret_token: H5dbRqPOOUho56SbG3bSMKKAHhOtgekQ3e4kvc5ZcffSso1PPh
access_token: 1432420093372342285-X8Ato3pHzwvvqfn4PfsdNNwHP1Dfx9
access_token_secret: qEf4dsbDib3TXwaBphhA0wc5DquHNCVghJkR5EPG8WjV4